export const FETCH_RECENT_MOVIES = "FETCH_RECENT_MOVIES";
export const FETCH_MOVIE_BY_ID = "FETCH_MOVIE_BY_ID";
export const FETCH_MOVIES_BY_CINEMA = "FETCH_MOVIES_BY_CINEMA";
export const FETCH_MOVIES_BY_PRODUCER = "FETCH_MOVIES_BY_PRODUCER";
